=== Lomowolo/MiniAutobiography/textbook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="textbooks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="textbook" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="authors">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="author" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="first_name" type="xs:string"/>
                                                    <xs:element name="last_name" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="publisher">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="website" type="xs:anyURI"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="year" type="xs:gYear"/>
                            <xs:element name="ISBN" type="xs:string"/>
                            <xs:element name="edition" type="xs:string"/>
                            <xs:element name="cover" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Lomowolo/MiniAutobiography/textbook.xml
<textbooks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="textbook.xsd">
    <textbook>
        <title>File system Forensics Analysis</title>
        <authors>
            <author>
                <first_name>Brian</first_name>
                <last_name>Carrier</last_name>
            </author>
        </authors>
        <publisher>
            <name>Addison Wesley</name>
            <website>http://www.awprofessional.com/</website>
        </publisher>
        <year>2005</year>
        <ISBN>032-1268172</ISBN>
        <edition>1st</edition>
        <cover>paperback</cover>
    </textbook>
    <textbook>
        <title>Cryptography and Network Security: Principles and Practice</title>
        <authors>
            <author>
                <first_name>William</first_name>
                <last_name>Stallings</last_name>
            </author>
        </authors>
        <publisher>
            <name>Pearson</name>
            <website>https://www.pearson.com</website>
        </publisher>
        <year>2017</year>
        <ISBN>978-0164444284</ISBN>
        <edition>7th</edition>
        <cover>hardcover</cover>
    </textbook>
</textbooks>
